version: '2'
services:
  apparmor:
    build:
      context: ./apparmor
      dockerfile: Dockerfile
    restart: 'no'
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
    environment:
      - 'ENFORCE=1'
    cap_add:
      - MAC_ADMIN
      - MAC_OVERRIDE
